FROM ruby:2.6.6

ENV WEBSERVER_PORT 3000
ENV DATABASE_HOST database
ENV DATABASE_PORT 5432
ENV DATABASE_PASSWORD hptlAhwZRoHK5mYCs

COPY . /webserver

WORKDIR /webserver

RUN gem install bundler -v 2.2.20
RUN bundle install

CMD ["bash", "-c", "while true; do sleep 1; done"]
